# Application Name
spring.application.name=ridex-backend

# Application Name

# Server Port
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ride_booking
spring.datasource.username=root
spring.datasource.password=Sanjay1234

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Show SQL
spring.jpa.show-sql=true

# SQL Format
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
wt.secret=8mN2xK9pQ4rT7vY1aD6fH3jL8zX5cB0nW9eR2uI7oP4qS6tV1yZ3gH8kL5mN2xQ
jwt.expiration=86400000


